var cardsfin = 
  [
    {
    "img":"media/vampknife.png",
    "name":"Vampyyriveitsi",
    "dmg":"1",
    "range":"1",
    "use":"4",
    "price":"750",
    "tooltip":"Riistä elämä",
    "desc":"Veitsi kaukaisesta transilvaniasta. Pelkän kivun ja kärsimyksen lisäksi, pisto veitsellä imaisee myös uhrilta elämänenergiaa.",
    "util":"Käyttäjä parantaa yhden osumapisteen osuttuaan viholliseen."
    },
    {
    "img":"media/rautaketju.png",
    "name":"Rautaketju",
    "dmg":"2",
    "range":"2",
    "use":"4",
    "price":"1000",
    "tooltip":"Selkää maistaa",
    "desc":'Painava rautainen ketju. Ketjuun on kaiverrettu teksti "K-rauta".',
    "util":"Osuma siirtää vihollista askeleen taaksepäin. Jos vihollinen on seinää vasten, ase tekee 3 osumapistettä vahinkoa."
    },
    {
    "img":"media/hadesketju.png",
    "name":"Hadesketju",
    "dmg":"3",
    "range":"2",
    "use":"3",
    "price":"1300",
    "tooltip":"Voi jättää jäljen",
    "desc":"Painava infernaalinen ketju syvältä Hadeksen kidutuskammioista. Hanskojen käyttö suositeltua.",
    "util":"Osuma siirtää vihollista kolme ruutua taaksepäin. Jos vihollinen on seinää vasten, ase tekee 4 osumapistettä vahinkoa."
    },
    {
    "img":"media/biketjukeihas.png",
    "name":"Bi-ketjukeihäs",
    "dmg":"2",
    "range":"3",
    "use":"3",
    "price":"1000",
    "tooltip":"Hyvä mellakoissa",
    "desc":"Erityinen kaksikärkinen keihäs. Nappulaa painamalla keihään kaksi titaanista kärkeä syöksyvät vauhdikkaasti suuntiinsa.",
    "util":"Hyökkäys tekee samanaikaisesti vahinkoa myös suoraan käyttäjän taakse kuin eteen."
    },
    {
    "img":"media/hakku20.png",
    "name":"Hakku 2.0",
    "dmg":"1",
    "range":"2",
    "use":"4",
    "price":"700",
    "tooltip":"100% lisää kipua",
    "desc":"Tuliase jonka perä on varustettu hakulla. Ase oli päämääräisesti kaivostyöläisten käytössä kolmannen maailmansodan aikana.", 
    "util":"Toimii samanaikaisesti hakkuna, ase menettää kaivamisesta myös osumapisteen kuin hyökkäämisestä."
    },
    {
    "img":"media/kaivuukarbiini.png",
    "name":"Kaivuukarbiini",
    "dmg":"1",
    "range":"4",
    "use":"5",
    "price":"1100",
    "tooltip":"Ota 2, maksa 1",
    "desc":"Tehokas tuliase jonka perä on varustettu hakulla. Ase oli päämääräisesti kaivostyöläisten/spesialistien käytössä kolmannen maailmansodan aikana.",
    "util":"Toimii samanaikaisesti hakkuna, ase menettää myös kaivamisesta osumapisteen kuin hyökkäämisestä."
    },
    {
    "img":"media/tikat.png",
    "name":"Tikat",
    "dmg":"2",
    "range":"3",
    "use":"5",
    "price":"500",
    "tooltip":"Et osaa heittää...",
    "desc":"Tikkoja. Teräviä tikkoja. Hauska peli näin pubeissa kun taas ihan kauneina kesäiltoinakin. Vaatii vakaata kättä ja tarkkuutta.",
    "util":"Hyökkäyksellä on 50% mahdollisuus mennä ohi, heitä kolikkoa tai jotain vastaavaa." 
    },
    {
    "img":"media/lihamagneetti.png",
    "name":"Lihamagneetti",
    "dmg":"1",
    "range":"6",
    "use":"4",
    "price":"800",
    "tooltip":"Vetovoimainen",
    "desc":"Erityinen magneetti, joka magnetisoi lihassoluja. Vetää voimakkaasti puoleensa kaikenmuotoisia organismeja lampaista ihmisiin. Teurastajan unelmatyökalu.",
    "util":"Vetää vihollisen viereiseesi ruutuun." 
    },  
    {
    "img":"media/1000veitsi.png",
    "name":"1000°F veitsi",
    "dmg":"3",
    "range":"1",
    "use":"4",
    "price":"900",
    "tooltip":"Käytä hanskoja!",
    "desc":"Keittiöveitsi, joka on kuumennettu äärimmäiseen lämpötilaan. Jostain syystä, veitsi ei jäähdy koskaan.",
    "util":"Hyökkäys tekee aina 3 osumapistettä vahinkoa, vaikka vihollisella olisi suojausta vahinkoa vastaan." 
    },  
    {
    "img":"media/grimoire.png",
    "name":"Grimoire",
    "dmg":"-",
    "range":"-",
    "use":"6",
    "price":"700",
    "tooltip":"Nukentekijän kirja",
    "desc":"Maaginen kirja jostain kaukaisesta maailmasta. Kosminen energia hohkaa kirjan sivuista...",
    "util":"Käyttäjä nostaa yhden punaisen kortin." 
    },  
    {
    "img":"media/codexgigas.png",
    "name":"Codex Gigas",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"500",
    "tooltip":"Hadeksen kirja",
    "desc":"Pirullinen kirja alamaailmasta. Pimeä energia hohkaa kirjan sivuista...",
    "util":"Käyttäjä nostaa yhden punaisen kortin + menettää yhden osumapisteen." 
    }, 
    {
    "img":"media/myyntitykki.png",
    "name":"Myyntitykki",
    "dmg":"2",
    "range":"2",
    "use":"-",
    "price":"500",
    "tooltip":"Pay 2 win!",
    "desc":"Panssarintorjuntaohjuksen rungosta rakennettu raskas tuliase. Ei lähimaksua.",
    "util":"Aseella ei ole osumapisteitä, mutta käyttö maksaa käyttäjältä 200 pistettä." 
    },
    {
    "img":"media/punakone.png",
    "name":"Punakone",
    "dmg":"2",
    "range":"4",
    "use":"-",
    "price":"600",
    "tooltip":"Suuri ja mahtava",
    "desc":"Panssarintorjuntaohjuksen rungosta rakennettu raskas tuliase. Aseen kyljessä on sirpin ja vasaran muotoiset symboolit.",
    "util":"Aseella ei ole osumapisteitä, mutta käyttö maksaa yhden punaisen kortin" 
    },
    {
    "img":"media/tyovoimasinko.png",
    "name":"Työvoimasinko",
    "dmg":"2",
    "range":"2",
    "use":"-",
    "price":"600",
    "tooltip":"Työturvariski!",
    "desc":"Ilmantorjuntaohjuksen rungosta rakennettu raskas tuliase. Raksatyöntekijän go-to.",
    "util":"Aseella ei ole osumapisteitä, mutta käyttö maksaa yhden osumapisteen joltain käyttäjän työkalulta." 
    },
    {
    "img":"media/ketamiini.png",
    "name":"Ketamiini",
    "dmg":"-",
    "range":"1",
    "use":"3",
    "price":"800",
    "tooltip":"Hyvää yötä kulta.",
    "desc":"Dissosiatiivista anestesiaa aiheuttava aine, jota käytetään usein nukutuksissa.",
    "util":"Hyökkäyksen kohde ohittaa seuraavan vuoronsa kokonaan." 
    },
    {
    "img":"media/prokaiini.png",
    "name":"Prokaiini",
    "dmg":"-",
    "range":"1",
    "use":"3",
    "price":"700",
    "tooltip":"Voimaton...olo...",
    "desc":"Esteri, jota käytetään paikallispuudutusaineena muun muassa hammashoidoissa. Tunnetaan myös nimellä novokaiini.",
    "util":"Hyökkäyksen kohde joutuu luopumaan yhdestä valitsemastasi passiivisesta kortista." 
    },
    {
    "img":"media/bentsokaiini.png",
    "name":"Bentsokaiini",
    "dmg":"-",
    "range":"1",
    "use":"3",
    "price":"600",
    "tooltip":"Ei nyt jaksais...",
    "desc":"Esteri, jota käytetään paikallispuudutusaineena muun muassa hammashoidoissa.",
    "util":"Hyökkäyksen kohde tekee hyökkäyksillään yhden osumapisteen vähemmän vahinkoa seuraavalla vuorollaan." 
    },
    {
    "img":"media/taikaluoti.png",
    "name":"Taikaluoti",
    "dmg":"2",
    "range":"4-8",
    "use":"4",
    "price":"600",
    "tooltip":"It is a magic",
    "desc":"Maaginen riimu, joka materialisoi sieluenergiaa ja laukaisee tehokkaan valoluodin. Luodilla kestää hetken aikaa ennen kun sen vaikutus on vahinkoa aiheuttavaa.",
    "util":"Vihollisen täytyy seistä vähintään neljän ruudun päässä jotta hyökkäys osuisi." 
    },
    {
    "img":"media/sielukeho.png",
    "name":"Sielu keho",
    "dmg":"1",
    "range":"5",
    "use":"5",
    "price":"500",
    "tooltip":"Muutoksia",
    "desc":"Maaginen riimu, joka materialisoi käyttäjän sieluenergian ja mahdollistaa sen siirtämisen.",
    "util":"Hyökkäyksen kohde vaihtaa paikkaa kanssasi." 
    },
    {
    "img":"media/teknonuoli.png",
    "name":"Teknonuoli",
    "dmg":"2",
    "range":"6",
    "use":"3",
    "price":"1300",
    "tooltip":"Kaiken läpi",
    "desc":"Heittonuoli, joka koostuu puhtaasta tiivistetystä valosta. Nuoli kuumenee riittävässä vauhdissa äärimmäisen kuumaksi.",
    "util":"Hyökkäys kulkee kaikkien vihollisten läpi ja vaikutus yltää aina kuuden askeleen päähän." 
    },
    {
    "img":"media/mustakynttila.png",
    "name":"Musta kynttilä",
    "dmg":"-",
    "range":"-",
    "use":"2",
    "price":"500",
    "tooltip":"Älä kuole vielä...",
    "desc":"Musta kynttilä, jonka pyhällä energialla siunattu liekki suojaa kantajan ruumista ja sielua kuolemalta.",
    "util":"Käyttäjä ei voi pudota alle yhden osumapisteen ennen seuraavaa vuoroaan."
    },
    {
    "img":"media/taikaohjus.png",
    "name":"Taikaohjus",
    "dmg":"1",
    "range":"4",
    "use":"5",
    "price":"1200",
    "tooltip":"Ohjautuva isku",
    "desc":"Maaginen riimu, joka laukaisee ammuksen tiivistettyä kosmista energiaa. Projektiilia voi ohjata ajatuksen voimalla.",
    "util":"Hyökkäyksen osumaetäisyys on vapaasti ohjattavissa 4 ruutua."
    },
    {
    "img":"media/elintuli.png",
    "name":"Elintuli",
    "dmg":"2",
    "range":"??",
    "use":"4",
    "price":"1000",
    "tooltip":"Elävä liekki",
    "desc":"Myyttinen soihtu alamaailmasta, joka sitoutuu käyttäjän sieluun. Jos liekki sammuu, soihtu vie sen kantajan mukanaan pois tuonpuoleiseen.",
    "util":"Aseen hyökkäysetäisyys = käyttäjän osumapisteet."
    },
    {
    "img":"media/jaaleka.png",
    "name":"Jääleka",
    "dmg":"2",
    "range":"1",
    "use":"4",
    "price":"700",
    "tooltip":"Älä nuolaise",
    "desc":"Raskas, suorastaan jäätävän kylmä vasara. Nuijan kärjen ytimen sisällä on absoluuttista nollapistettäkin pienemmät lämpötilat.",
    "util":"Hyökkäyksen kohde liikkuu 2 askelta vähemmän seuraavalla vuorollaan."
    },
    {
    "img":"media/tahdenlento.png",
    "name":"Tähdenlento",
    "dmg":"2",
    "range":"5",
    "use":"4",
    "price":"1200",
    "tooltip":"Pois alta!!",
    "desc":"Maaginen riimu, joka muodostaa käyttäjän ympärille uskomattoman kuuman auran ja heittää käyttäjän vauhdilla eteenpäin. Kuvauksen hurjuudesta huolimatta, prosessi ei aiheuta varsinaisia vaaratilanteita muille kuin hyökkäyksen edessä seisoville onnettomille kohteille.",
    "util":"Käyttäjä liikkuu 5 askelta eteenpäin ja vahongoittaa kaikkia välissä seisovia pelaajia."
    },
    {
    "img":"media/quattrokeihas.png",
    "name":"Quattrokeihäs",
    "dmg":"2",
    "range":"3",
    "use":"3",
    "price":"1200",
    "tooltip":"Nimi kertoo kaiken",
    "desc":"Matemaattisesti ainakin 2 kertaa parempi kuin Bi-ketjukeihäs. C'mon, neljä terävää titaanista kärkeä! Melkoista.",
    "util":"Hyökkäys tekee samanaikasesti vahinkoa kaikkiin ilmansuuntiin."
    },
    {
    "img":"media/kuningasvesi.png",
    "name":"Kuningasvesi",
    "dmg":"1",
    "range":"2",
    "use":"4",
    "price":"900",
    "tooltip":"Vahvasti syövyttävä",
    "desc":"Voimakkaasti syövyttävä väkevän suolahapon ja väkevän typpihapon seos. Tämä happo syövyttää jopa kultaa ja platinaa, joten kuvittele vain minkälainen vaikutus sillä on avutonta ihmistä vastaan.",
    "util":"Käyttäjä poistaa hyökkäyksen kohteelta yhden satunnaisen punaisen kortin."
    },
    {
    "img":"media/varjopeili.png",
    "name":"Varjopeili",
    "dmg":"??",
    "range":"??",
    "use":"4",
    "price":"1100",
    "tooltip":"Sitä saa mitä tilaa",
    "desc":"Myyttinen pimeää energiaa kuhiseva käsipeili, joka materialisoi ja luo hetkellisen kopion siihen heijastuneesta objektista.",
    "util":"Käyttäjä voi kopioida minkä tahansa vihollisen aseen efektin, mukaan lukien hyökkäyksen etäisyyden etäisyyden ja vahingon."
    },
    {
    "img":"media/mestarikipina.png",
    "name":"Mestarikipinä",
    "dmg":"3",
    "range":"5",
    "use":"3",
    "price":"2000",
    "tooltip":"Rakkauden värinen",
    "desc":"Maaginen riimu jostain kaukaisesta maailmasta. Hyökkäys kerää ympäröivää energiaa sekä valoa ja laukaisee massiivisen säteen puhdasta tiivistettyä tuhoa, joka loistaa kauniisti kaikilla spektrin väreillä.",
    "util":"Hyökkäys vaikuttaa 3 ruutua leveään alueeseen 5 ruudun päähän."
    },
    {
    "img":"media/elintera.png",
    "name":"Elinterä",
    "dmg":"3",
    "range":"3",
    "use":"OP",
    "price":"800",
    "tooltip":"Elävä kohtalo",
    "desc":"Kuoleman palvelijattaren enigmaattinen viikate, jolla on yhteys tuonpuoliseen. Käyttäjän henki ja kohtalo sidotaan viikatteen terään.",
    "util":"Aseen osumapisteet ovat samat kuin käyttäjän osumapisteet. Aseen käyttö maksaa siis käyttäjältä yhden osumapisteen, ja jos ase menettää osumapisteen niin käyttäjällä on sama kohtalo. "
    },
    {
    "img":"media/zsademiekka.png",
    "name":"Z-sädemiekka",
    "dmg":"1",
    "range":"2",
    "use":"6",
    "price":"800",
    "tooltip":"Kombinaatioisku",
    "desc":"Kevyt ja kompakti valomiekka jostain toisesta maailmasta. Aseen keveys mahdollistaa sen nopean ja sulavan käytön.",
    "util":"Hyökkäystä voi käyttää 3 kertaa vuoron aikana."
    },
    {
    "img":"media/verinenkoukku.png",
    "name":"Verinen koukku",
    "dmg":"-",
    "range":"3",
    "use":"4",
    "price":"700",
    "tooltip":"Eh, ketsuppia vaan",
    "desc":"Iso ruosteinen koukku, joka on upotettu johonkin kummalliseen punaiseen nesteeseen. Näyttää lähinnä pilaantuneelta ketsupilta, mutta voi oikeastaan olla mitä vaan. Ei kannata maistaa.",
    "util":"Käyttäjä voi ottaa hyökkäyksen kohteelta yhden punaisen kortin."
    },
    {
    "img":"media/teknonoppa.png",
    "name":"Teknonoppa",
    "dmg":"-",
    "range":"-",
    "use":"2",
    "price":"800",
    "tooltip":"Yritä uudestaan",
    "desc":"Analogisen nopat ovat niin eilistä, tervetuloa digiaikaan! Tämä teknologisesti kehittynyt noppa on tehty puhtaasta energiasta ja sisältää paljon jännittäviä lisäominaisuuksia, mm. herätyskellon.",
    "util":"Käyttäjä saa kokonaan uuden heittovuoron."
    },
    {
    "img":"media/partatera.png",
    "name":"Partaterä",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"400",
    "tooltip":"Ranteet auki",
    "desc":"Ihana kipu. Muista; tietä pitkin, ei sen yli.",
    "util":"Käyttäjä saa 300 pistettä + menettää yhden osumapisteen."
    },
    {
    "img":"media/taikaluoti20.png",
    "name":"Taikaluoti v2.0",
    "dmg":"99",
    "range":">5<",
    "use":"1",
    "price":"500",
    "tooltip":"Kielletty 57 maassa",
    "desc":"Äärimmäisen tappava modifikaatio Taikaluodista. Laukaisee uskomattoman tehokkaan valoluodin, joka likvidoi uhrin elimet millisekunneissa. Riimu luokitellaan niin julmaksi, että kansainväliset humanitaariset oikudet kieltää sen käytön sodankäynnissä. Vaarallisuudesta huolimatta, riimun osumaetäisyydelliset puutteet tekevät siitä hyvin epäkäytännöllisen taistelutilanteissa.",
    "util":"Hyökkäys toimii ainoastaan viiden ruudun päässä sijaitsevaan kohteeseen."
    },
    {
    "img":"media/antimiekka.png",
    "name":"Antimiekka",
    "dmg":"1",
    "range":"1",
    "use":"4",
    "price":"800",
    "tooltip":"Aidosti epäaito",
    "desc":"Miekka, joka on tuotu jostain kaukaisesta rinnakkaisuniversumista. Transportaation yhteydessä tapahtuneen temporaalisen erheen takia, osa miekan rakenteellisesta datasta katosi aika-avaruuteen ja se ei materialisoitunut oikein. Miekka on erittäin epävakaassa tilassa, ja sen käytöllä voi olla peruuttamattomia vaikutuksia tällä maailmanviivalla.",
    "util":"Hyökkäyksen kohde menettää 200 pistettä."
    },
    {
    "img":"media/isolaastari.png",
    "name":"Iso laastari",
    "dmg":"-",
    "range":"-",
    "use":"3",
    "price":"700",
    "tooltip":"Isoille haavoille!",
    "desc":"Saitko puukosta? Rynnäkkökiväärin luodista? Ei hätää! Tämä nanoteknologiaa hyödyntävä isokokoinen laastari korjaa moiset pikku haaverit sekunneissa.",
    "util":"Käyttäjä parantaa 2 osumapistettä."
    },
    {
    "img":"media/adrestiantera.png",
    "name":"Adrestian terä",
    "dmg":"-",
    "range":"3",
    "use":"5",
    "price":"700",
    "tooltip":"Pyhä retribuutio",
    "desc":"Tasapainon jumalattaren pyhä miekka, joka suljettiin pois tyhjiöön tuhansia vuosia sitten. Hyvän ja pahan tasapaino on sidottu miekan terään.",
    "util":"Asettaa hyökkäyksen kohteelle saman määrän osumapisteitä kun käyttäjällä."
    },
    {
    "img":"media/rikasote.png",
    "name":"Rikas ote",
    "dmg":"-",
    "range":"2",
    "use":"3",
    "price":"700",
    "tooltip":"Raha kiertämään",
    "desc":"Maaginen riimu. Käyttää telekineettistä energiaa ja liikuttaa kolikoita sun muita arvoesineitä. Erityisessä suosiossa pienissä kriminaalirganisaatioissa.",
    "util":"Käyttäjä ottaa hyökkäyksen kohteelta 200 pistettä."
    },
    {
    "img":"media/heikentavaote.png",
    "name":"Heikentävä ote",
    "dmg":"-",
    "range":"2",
    "use":"3",
    "price":"500",
    "tooltip":"Ei väkivaltaa!",
    "desc":"Maaginen riimu. Riimun energia tylsyttää mahdolliset terävät reunat ja vaporisoi ruudin. Yleisesti virkavallan käytössä.",
    "util":"Käyttäjä voi poistaa joltain hyökkäyksen kohteen aseelta yhden osumapisteen."
    },
    {
    "img":"media/jaatavaote.png",
    "name":"Jäätävä ote",
    "dmg":"-",
    "range":"2",
    "use":"3",
    "price":"400",
    "tooltip":"-50°C",
    "desc":"Maaginen riimu. Riimun energiä viilentää ilmaa huomattavasti. Hyödyllinen, jos vaikka pakastin hajoaa tai jotain.",
    "util":"Hyökkäyksen kohde liikkuu 5 ruutua vähemmän seuraavalla vuorollaan."
    },
    {
    "img":"media/pimeaote.png",
    "name":"Pimeä ote",
    "dmg":"-",
    "range":"5",
    "use":"3",
    "price":"400",
    "tooltip":"Liikun itsestään",
    "desc":"Maaginen riimu. Erittää heikohkoa telekineettistä energiaa, jota pystyy käyttää pienien-keskikokoisten objektien ja asioiden liikuttamiseen. Hyödyllinen, jos haluat vaikka sisustaa kotisi uusiksi tai jotain.",
    "util":"Käyttäjä voi siirtää hyökkäyksen kohdetta 2 ruutua mihin tahansa suuntaan."
    },
    {
    "img":"media/millennium.gif",
    "name":"Millennium",
    "dmg":"3",
    "range":"6",
    "use":"6",
    "price":"2200",
    "tooltip":"Ikuisesti",
    "desc":"Huipputehokas laserkivääri kaukaisesta tulevaisuudesta.",
    "util":"Hyökkäystä voi käyttää 2 kertaa vuoron aikana."
    },
    {
    "img":"media/giga.gif",
    "name":"Gigatekninen",
    "dmg":"4",
    "range":"8",
    "use":"4",
    "price":"2200",
    "tooltip":"Hae ja tuhoa",
    "desc":"---",
    "util":"Hyökkäyksen osumaetäisyys on vapaasti ohjattavissa 8 ruutua."
    },
    {
    "img":"media/betel.gif",
    "name":"Betelgeuze",
    "dmg":"5",
    "range":"7x7",
    "use":"4",
    "price":"2200",
    "tooltip":"RÄJÄYTÄ KAIKKI!!",
    "desc":"---",
    "util":"---"
    },
    {
    "img":"media/atma.gif",
    "name":"Atma",
    "dmg":"8",
    "range":"3",
    "use":"4",
    "price":"2200",
    "tooltip":"Elämä",
    "desc":"---",
    "util":"---"
    },
    {
    "img":"media/ame.gif",
    "name":"Ame no Nuhoko",
    "dmg":"4",
    "range":"4",
    "use":"5",
    "price":"2200",
    "tooltip":"Luonti",
    "desc":"---",
    "util":"---"
    },
    {
    "img":"media/orionis.gif",
    "name":"Orionis",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"2200",
    "tooltip":"Heaven",
    "desc":"---",
    "util":"---"
    },
    {
    "img":"media/bootes.gif",
    "name":"Boötes",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"2200",
    "tooltip":"Void",
    "desc":"---",
    "util":"---"
    }
]
var cards2fin = 
  [
    {
    "img":"media/koukkusauva.png",
    "name":"Koukkusauva",
    "tooltip":"Kättä pidempää",
    "desc":"Insinööriajattelun mestarinäyte, pitkä sauva jonka kärki on taitettu koukuksi. Toimii myös selänrapsuttimena! Mitä muuta ihminen edes tarvitsee?!",
    "util":"Kaikkien käyttäjän aseiden hyökkäysetäisyys +1.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/savuke.png",
    "name":"Savuke",
    "tooltip":"Olet nyt siisti.",
    "desc":"Tupakointi tappaa. Rökning döda.",
    "util":"Käyttäjä saa 200 pistettä aina ottaessaan vahinkoa.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/pyhamanteli.png",
    "name":"Pyhä manteli",
    "tooltip":"Taivaista pudonnut",
    "desc":"Täysin tavallinen manteli, joka on jostain syystä siunattu pyhällä energialla. Kuka siunaisi mantelin ja miksi? Ken tietää.",
    "util":"Jos käyttäjällä on 2 osumapistettä tai enemmän, tämä jää yhteen osumapisteeseen vaikka vihollisen hyökkäys olisi fataali.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/sydanriipus.png",
    "name":"<3 riipus",
    "tooltip":"The power of love",
    "desc":"Kaunis sydämen muotoinen riipus. Erinomainen lahjaidea rakkaalle, tai henkilölle jolla on ongelmia terveytensä kanssa.",
    "util":"Jos käyttäjällä on vuoron alussa < 3 osumapistettä, tämä parantaa yhden osumapisteen.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/muistikampa.png",
    "name":"Muistikampa",
    "tooltip":"8GB DDR3",
    "desc":"Tietokoneen keskusmuistia. Todella vanhaa teknologiaa...",
    "util":"Käyttäjä voi pitää kädessään rajattoman määrän punaisia kortteja.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/demoninsarvi.png",
    "name":"Demonin sarvi",
    "tooltip":"Sisäinen raivo >:(",
    "desc":"Pieni ja siro sarvi jostain kaukaisesta maailmasta. Sarvi hohtaa vaaleanpunaisena, ja tekee käyttäjän jostain syystä hyvin aggressiiviseksi.",
    "util":"Kaikkien käyttäjän aseiden vahinko +1.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/jeesusteippi.png",
    "name":"Jeesusteippi",
    "tooltip":"Ghetto tuunaus",
    "desc":"Tunnetaan ehkä paremmin nimellä ilmastointiteippi. Ei ole mitään asiaa missään maailmaassa mitä tämä legendaarinen teippi ei korjaisi.",
    "util":"Käyttäjä voi 'yhdistää' kaksi asettaan ja hyökätä näillä samanaikaisesti. Kummankin aseen vaikutukset ovat voimassa, mutta vahinko, etäisyys sekä käyttökerrat määrittyvät aseen mukaan jolla nämä arvot ovat korkeammat. Aseilla ei voi tämän jälkeen enää hyökätä erikseen.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/neliaplia.png",
    "name":"Neliapila",
    "tooltip":"Ikuinen rikkaus",
    "desc":"Nelilehtisten apiloiden kerrotaan lupaavan hyvää onnea, mutta viisi lehteä? Kuusi lehteä? Huonoja asioita tiedossa, man.",
    "util":"Käyttäjä saa 100 pistettä joka vuoronsa alussa.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/combobulaattori.png",
    "name":"Combobulaattori",
    "tooltip":"combobuloi",
    "desc":"Todella kummallinen... teknologinen kuutio. Siniseen suppiloon on piirretty tussilla epämääräisesti miekan kuva, ja punaiseen paljon dollarimerkkejä. Kuviot näyttää joltain viisi-vuotiaan raapustuksilta...",
    "util":"Milloin tahansa pelin aikana, käyttäjä voi vaihtaa yhden aseensa joko 2 osumapisteeseen tai 300 pisteeseen.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/opiskelijakortti.png",
    "name":"Opiskelijakortti",
    "tooltip":"Kenen se on?!",
    "desc":"Jonkin kaukaisen korkeakoulun opiskelijakortti. Kortti on huonossa kunnossa, likainen ja kulunut. Sen teksteistä on vaikea saada selvää...",
    "util":"Käyttäjä saa jokaisesta kaupan tuotteesta 100 pisteen alennuksen.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/ristiriipus.png",
    "name":"Ristiriipus",
    "tooltip":"Varjeltu",
    "desc":"Kaunis kultainen risti. Koruun sulautettu jalokivi on siunattu pyhällä energialla.",
    "util":"Aina kun käyttäjä on ottamassa vahinkoa, tämä heittää noppaa. Jos luku on 6, käyttäjä ei ota vahinkoa.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/d6.png",
    "name":"D6",
    "tooltip":"Parempi käsi",
    "desc":"Kuusivuinen noppa. Kätevä jos haluaa pelata lautapeleja tai jotain, tosin kuka edes pelaa lautapelejä nykyään hahhahaha",
    "util":"Aina vuoronsa alussa, käyttäjä voi vaihtaa haluamansa määrän punaisia kortteja uusiin.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/kysymysriipus.png",
    "name":'"?" riipus',
    "tooltip":"mitääh",
    "desc":"Mysteerinen kysymysmerkkiriipus. Koru saattaa satunnaisesti päästellä kummallisia ääniä. Saattaa myös repäistä hauskan vitsin aina silloin tällöin.",
    "util":'Aina vuoronsa alussa, käyttäjä voi halutessaan nostaa vihreän "?" kortin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/illuusio.png",
    "name":"Illuusio",
    "tooltip":"Mindfreak",
    "desc":"Ovatko viivat suorassa vai vinossa, hä, hä?!",
    "util":"Käyttäjä voi liikkua valkoisten tyhjien kohtien läpi ja siirtyä suoraan tyhjän kohdan toisella puolella olevaan ruutuun.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/litteaarkku.png",
    "name":"Litteä arkku",
    "tooltip":"Pienelle kullalle?",
    "desc":"Tähän sirorakenteiseen arkkuun ei mahdu paljon tavaraa, mutta itse ajatushan on se mikä on toki tärkeintä. Arkussa on lukko, mutta mekanismi ei näytä olevan toimintakunnossa...",
    "util":"Käyttäjä saa kaikki pistemäärät 200 tai alle kaksinkertaisena.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/aktiiviranneke.png",
    "name":"Aktiiviranneke",
    "tooltip":"Ylös ja juoksuun",
    "desc":"Kätevä ranteen ympärille sidottava kapistus, joka laskee kaikenlaista tärkeää käyttäjän askelmäärästä päivittäiseen kalorinkulukseen. Toimii vielä jotenkuten, vaikka ajurit kylläkin kaipaisivat pientä päivittämistä.",
    "util":"Aina kun käyttäjä liikkuu 6 ruutua tai enemmän kerralla, tämä saa 300 pistettä.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/antimateria.png",
    "name":"Antimateria",
    "tooltip":"Taskuvaraus",
    "desc":"Kummallinen ja vaarallinen aine, joka on kerätty jostain kaukaisesta avaruudesta. Ainetta on käytetty jo vuosikausia kloonaamisessa. Ei saa missään tapauksessa olla kosketuksessa paljasta ihoa vasten.",
    "util":"Käyttäjä voi vuorollaan täyttää jonkun aseensa osumapisteet, mutta menettää yhden osumapisteen + aseen hinnan määrän pisteitä.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    }  
]
var cards3fin = 
  [
    {
    "img":"media/teleport.png",
    "name":"Teleport",
    "util":"Käyttäjä siirtyy kotiruutuunsa.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/puuska.png",
    "name":"Puuska",
    "util":"Siirtää vihollista 3 ruutua taaksepäin, käyttöetäisyys 2 ruutua.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/puhallin.png",
    "name":"Puhallin",
    "util":"Siirtää vihollista 5 ruutua taaksepäin, käyttöetäisyys 2 ruutua.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/mysteeri.png",
    "name":"Mysteeri!",
    "util":'Käyttäjä nostaa 3 vihreää "?" korttia.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/megamysteeri.png",
    "name":"Megamysteeri!!",
    "util":'Käyttäjä nostaa 4 vihreää "?" korttia.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/wtf.png",
    "name":"Mitä helvettiä",
    "util":'Käyttäjä nostaa 5 vihreää "?" korttia.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/booster.png",
    "name":"Booster",
    "util":'Käyttäjä voi siirtyä 1-2 ruutua eteenpäin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/bigbooster.png",
    "name":"Big booster",
    "util":'Käyttäjä voi siirtyä 1-3 ruutua eteenpäin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/bbbooster.png",
    "name":"BBBBBooster",
    "util":'Käyttäjä voi siirtyä 1-5 ruutua eteenpäin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/korjaus.png",
    "name":"Korjaus",
    "util":'Käyttäjä parantaa yhden osumapisteen jollekkin aseelleen.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/kaivuu.png",
    "name":"Kaivuu",
    "util":'Toimii kertakäyttöisenä hakkuna.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/napistus.png",
    "name":"Näpistys",
    "util":'Käyttäjä varastaa viholliselta 100 pistettä, käyttöetäisyys 1 ruutu.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/kilpi.png",
    "name":"Kilpi",
    "util":'Kun käyttäjä on ottamassa vahinkoa, hän voi käyttää korttia ja välttää vahingon.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/ensiapu.png",
    "name":"Ensiapu",
    "util":'Käyttäjä parantaa yhden osumapisteen.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/magneto.png",
    "name":"Magneto",
    "util":' Käyttäjä vetää vihollisen viereiseen ruutuun, käyttöetäisyys 5 ruutua.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/paivitys.png",
    "name":"Päivitys",
    "util":'Vaihtaa kaikki kaupan tuotteet uusiin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/solve.png",
    "name":"solve( )",
    "util":'Käyttäjä voi katsoa kummankin "?" pakan päällimmäisen kortin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/jumalasilma.png",
    "name":"Jumalan silmä",
    "util":'Käyttäjä voi katsoa kenen tahansa pelaajan kaikki punaiset kortit.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/harhautus.png",
    "name":"Harhautus",
    "util":'Käyttäjä poistaa vihollisen kädestä 2 satunnaista punaista korttia, käyttöetäisyys 1 ruutu.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/lahja.png",
    "name":"Lahja!",
    "util":'Vihollinen nostaa 2 "?" korttia, käyttöetäisyys 2 ruutua.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/epasuoraisku.png",
    "name":"Epäsuora isku",
    "util":'Poistaa joltain vihollisen aseelta yhden osumapisteen.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/diili.png",
    "name":"Diili",
    "util":'Käyttäjä vaihtaa yhden aseistaan johonkin vihollisen aseeseen, käyttöetäisyys 1 ruutu.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/teroitus.png",
    "name":"Teroitus",
    "util":'Käyttäjän aseiden vahinko +1 yhden vuoron ajan.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/pitkitys.png",
    "name":"Pitkitys",
    "util":'Käyttäjän aseiden osumaetäisyys +1 yhden vuoron ajan.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/teleother.png",
    "name":"Teleother",
    "util":'Käyttäjä voi siirtää vihollisen mihin tahansa ruutuun, käyttöetäisyys 2 ruutua.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/teleport20.png",
    "name":"Teleport v2.0",
    "util":'Käyttäjä voi siirtyä mihin tahansa ruutuun.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/napistus20.png",
    "name":"Näpistys v2.0",
    "util":'Käyttäjä varastaa viholliselta 200 pistettä, käyttöetäisyys 2 ruutua.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
]