var cards = 
  [
    {
    "img":"media/vampknife.png",
    "name":"Vampire Knife",
    "dmg":"1",
    "range":"1",
    "use":"4",
    "price":"750",
    "tooltip":"Take a life",
    "desc":"A special knife from deep transylvania. Aside from being painful, a stab with this glowing red knife saps away life-energy from the victim.",
    "util":"The user heals one hitpoint upon inflicting damage to an enemy."
    },
    {
    "img":"media/rautaketju.png",
    "name":"Iron chain",
    "dmg":"2",
    "range":"2",
    "use":"4",
    "price":"1000",
    "tooltip":"May leave a mark",
    "desc":'A heavy, rugged iron chain. Appears to be bought from a regular hardware store.',
    "util":"Moves the targeted enemy one tile back. If the enemy is positioned against a wall, this weapon deals three damage."
    },
    {
    "img":"media/hadesketju.png",
    "name":"Hades chain",
    "dmg":"3",
    "range":"2",
    "use":"3",
    "price":"1300",
    "tooltip":"100% leaves a mark",
    "desc":"A heavy, infernal chain deep from the chambers of the underworld. Used for torture purposes, probably.",
    "util":"Moves the targeted enemy three tiles back. If the enemy is positioned against a wall, this weapon deals four damage."
    },
    {
    "img":"media/biketjukeihas.png",
    "name":"Bi-chainspear",
    "dmg":"2",
    "range":"3",
    "use":"3",
    "price":"1000",
    "tooltip":"Great for rioting",
    "desc":"A unique double-ended spear. Pressing the button causes the two titanium spears to launch forward at great speeds.",
    "util":"Simultaneously deals damage in front of and behind the user."
    },
    {
    "img":"media/hakku20.png",
    "name":"Pickaxe 2.0",
    "dmg":"1",
    "range":"2",
    "use":"4",
    "price":"700",
    "tooltip":"100% more pain",
    "desc":"A compact handgun that comes equipped with a pickaxe stock. The weapon was mainly used by miners/soldiers during world war III.", 
    "util":"This weapon can also be used as a pickaxe. Both mining and attacking drain one use from the weapon."
    },
    {
    "img":"media/kaivuukarbiini.png",
    "name":"Minecarbine",
    "dmg":"1",
    "range":"4",
    "use":"5",
    "price":"1100",
    "tooltip":"One + one free",
    "desc":"A powerful rifle that comes equipped with a pickaxe stock. The weapon was mainly used by specialists during world war III.",
    "util":"This weapon can also be used as a pickaxe. Both mining and attacking drain one use from the weapon."
    },
    {
    "img":"media/tikat.png",
    "name":"Darts",
    "dmg":"2",
    "range":"3",
    "use":"5",
    "price":"500",
    "tooltip":"You can't throw...",
    "desc":"Darts. Pointy, pointy darts. A fun activity during a hot summer day. Requires a stable hand and some concentration, but you'll probably miss anyway. It's not easy!",
    "util":"Has a 50% chance of missing the enemy." 
    },
    {
    "img":"media/lihamagneetti.png",
    "name":"Meatmagnet",
    "dmg":"1",
    "range":"6",
    "use":"4",
    "price":"800",
    "tooltip":"Make meat meet",
    "desc":"Very popular in modern slaughterhouses, this special magnet magnetizes cells in the muscle. Attract and pulls in most living organisms. Avoid pointing towards your own body.",
    "util":"Pulls the targeted enemy to the tile next to you." 
    },  
    {
    "img":"media/1000veitsi.png",
    "name":"1000°F knife",
    "dmg":"3",
    "range":"1",
    "use":"4",
    "price":"900",
    "tooltip":"Use gloves!",
    "desc":"Just a kitchen knife someone heated up. For some reason, this knife will never cool down.",
    "util":"This weapon always deals three hitpoints of damage, even if the targeted enemy has immunity/increased defense." 
    },  
    {
    "img":"media/grimoire.png",
    "name":"Grimoire",
    "dmg":"-",
    "range":"-",
    "use":"6",
    "price":"700",
    "tooltip":"Doll maker's book",
    "desc":"A magical book from a far-away world. Cosmic energy emanates from the pages of the book...",
    "util":"The user draws one red card." 
    },  
    {
    "img":"media/codexgigas.png",
    "name":"Codex Gigas",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"500",
    "tooltip":"Hades' book",
    "desc":"A wicked book deep from the underworld. Dark energy emanates from the pages of the book...",
    "util":"The user draws one red card and loses one hitpoint." 
    }, 
    {
    "img":"media/myyntitykki.png",
    "name":"Cashcannon",
    "dmg":"2",
    "range":"2",
    "use":"-",
    "price":"500",
    "tooltip":"Pay 2 win!",
    "desc":"A heavy bazooka-like weapon built from the remains of an anti-tank missile. Doesn't accept credit.",
    "util":"Using this weapon costs 200 points from the player." 
    },
    {
    "img":"media/punakone.png",
    "name":"The Red Machine",
    "dmg":"2",
    "range":"4",
    "use":"-",
    "price":"600",
    "tooltip":"United forever",
    "desc":"A heavy bazooka-like weapon built from the remains of an anti-tank missile. Use for friendship and labour.",
    "util":"Using this weapon costs one red card from the player. The player may choose which red card to discard." 
    },
    {
    "img":"media/tyovoimasinko.png",
    "name":"Workforcer",
    "dmg":"2",
    "range":"2",
    "use":"-",
    "price":"600",
    "tooltip":"A safety risk!",
    "desc":"A heavy bazooka-like weapon built from the remains of an anti-air missile. Work hard, play hard.",
    "util":"Using this weapon will instead use one hitpoint from one of the user's tools." 
    },
    {
    "img":"media/ketamiini.png",
    "name":"Ketamine",
    "dmg":"-",
    "range":"1",
    "use":"3",
    "price":"800",
    "tooltip":"Good night, love.",
    "desc":"A syringe of ketamine, a medication used for starting anesthesia. Induces pain relief, sedation, and memory loss.",
    "util":"The targeted enemy must skip the next turn." 
    },
    {
    "img":"media/prokaiini.png",
    "name":"Procaine",
    "dmg":"-",
    "range":"1",
    "use":"3",
    "price":"700",
    "tooltip":"Feel...weak...",
    "desc":"A syringe of procaine, a local anesthetic drug belonging to the amino ester group. Used primarily as an anesthetic for pain relief.",
    "util":"The targeted enemy loses one passive power card. They may choose which card to discard." 
    },
    {
    "img":"media/bentsokaiini.png",
    "name":"Benzocaine",
    "dmg":"-",
    "range":"1",
    "use":"3",
    "price":"600",
    "tooltip":"Not feeling up to it rn...",
    "desc":"A syringe of benzocaine, a local anesthetic drug belonging to the amino ester group. Used primarily as an anesthetic for pain relief.",
    "util":"The targeted enemy will deal one hitpoint of damage less during their next turn." 
    },
    {
    "img":"media/taikaluoti.png",
    "name":"Magic bullet",
    "dmg":"2",
    "range":"4-8",
    "use":"4",
    "price":"600",
    "tooltip":"It is a magic",
    "desc":"A magical rune. Materializes energy from the user's soul and launches forward a powerful bolt of energy. The bolt will have to travel for a while before reaching it's full potential.",
    "util":"The attack will only land if the enemy is 4-8 away tiles from the user." 
    },
    {
    "img":"media/sielukeho.png",
    "name":"Soul body",
    "dmg":"1",
    "range":"5",
    "use":"5",
    "price":"500",
    "tooltip":"Changes",
    "desc":"A magical rune. Materializes energy from the user's soul and launches forward a powerful luminous cluster of energy in the shape of the user. When in contact with an enemy, the user's soul will be transferred in place of the enemy and vice versa.",
    "util":"The targeted enemy switches places with the user." 
    },
    {
    "img":"media/teknonuoli.png",
    "name":"Teknoarrow",
    "dmg":"2",
    "range":"6",
    "use":"3",
    "price":"1300",
    "tooltip":"Through everything",
    "desc":"A javelin-like weapon made from pure light. The javelin will heat up to incredibly high temperatures when thrown. Revolutionalized the use of light-based weaponry that later became commonplace during the latter parts of world war III, mainly during the galactic conflict.",
    "util":"The attack will continue to travel and have effect even when hitting an enemy standing in it's path." 
    },
    {
    "img":"media/mustakynttila.png",
    "name":"Black candle",
    "dmg":"-",
    "range":"-",
    "use":"2",
    "price":"500",
    "tooltip":"Please hang on...",
    "desc":"A mysterious black candle that is blessed with holy energy. The holy aura emanating from the eternal flame will protect the user from death.",
    "util":"The user will stay on one hitpoint even if an attack was fatal."
    },
    {
    "img":"media/taikaohjus.png",
    "name":"Magic missile",
    "dmg":"1",
    "range":"4",
    "use":"5",
    "price":"1200",
    "tooltip":"Homing attack",
    "desc":"A magical rune. Launches a slow moving projectile of condensed cosmic energy. The user can control the projectile with the power of their mind, although this requires deep concentraion. I'm sure you can do it.",
    "util":"The user can control the path the attack will travel by."
    },
    {
    "img":"media/elintuli.png",
    "name":"Flame of living",
    "dmg":"2",
    "range":"??",
    "use":"4",
    "price":"1000",
    "tooltip":"Living flame",
    "desc":"A mythical torch deep from the underworld. The torch form's a bond with the user's soul that controls the intensity of the unholy flame. When the holder passes on, the torch will take the user's soul to the beyond.",
    "util":"The attack range of the weapon = the user's current hitpoints."
    },
    {
    "img":"media/jaaleka.png",
    "name":"Frozen maul",
    "dmg":"2",
    "range":"1",
    "use":"4",
    "price":"700",
    "tooltip":"Don't give it a lick",
    "desc":"A heavy, frozen hammer. The core of the hammer reaches temperatures near absolute zero. Pretty cool.",
    "util":"The targeted enemy will move two tiles less during their next turn."
    },
    {
    "img":"media/tahdenlento.png",
    "name":"Comet strike",
    "dmg":"2",
    "range":"5",
    "use":"4",
    "price":"1200",
    "tooltip":"Outta my way!!",
    "desc":"A magical rune. When used, the spell forms a searing hot aura around the user and enables them to dash forward at a great speed. Despite sounding dangerous, the effects of the rune are totally safe for the user. Only people in danger are the ones standing in front of the dash.",
    "util":"The user will move five tiles forward and damage any enemy standing in the way."
    },
    {
    "img":"media/quattrokeihas.png",
    "name":"Quadrospear",
    "dmg":"2",
    "range":"3",
    "use":"3",
    "price":"1200",
    "tooltip":"Better for rioting",
    "desc":"Mathematically speaking, this weapon is at least two times better than bi-chainspear. I mean come on, four sharp titanium spears! Doesn't get much better than that.",
    "util":"Simultaneously deals damage to all four directions around the user."
    },
    {
    "img":"media/kuningasvesi.png",
    "name":"Aqua regia",
    "dmg":"1",
    "range":"2",
    "use":"4",
    "price":"900",
    "tooltip":"Highly corrosive",
    "desc":"A highly corrosive mixture of nitric acid and hydrochloric acid. This yellow-orange fuming liquid can dissolve most metals, including the noble metals gold and platinum. Just imagine the effect it can have on exposed human skin! ",
    "util":"The targeted enemy loses one randomly picked red card."
    },
    {
    "img":"media/varjopeili.png",
    "name":"Shadow mirror",
    "dmg":"??",
    "range":"??",
    "use":"4",
    "price":"1100",
    "tooltip":"Reflect and deflect",
    "desc":"A mythical mirror infused with a mysterious dark energy. Materializes and creates a temporary copy of any object that it reflects. The source of the dark energy infused within the mirror is unknown.",
    "util":"The user can copy any of the targeted enemy's items for the turn, including damage and attack range."
    },
    {
    "img":"media/mestarikipina.png",
    "name":"Master spark",
    "dmg":"3",
    "range":"5",
    "use":"3",
    "price":"2000",
    "tooltip":"Love coloured",
    "desc":"A wonderful magical rune from a far-away world. The spell collects surrounding light and launches a supermassive ray of pure unadultered destruction that glows beautifully with all the colors of the spectrum.",
    "util":"The attack reaches an area three tiles wide in front of the user."
    },
    {
    "img":"media/elintera.png",
    "name":"Edge of living",
    "dmg":"3",
    "range":"3",
    "use":"OP",
    "price":"800",
    "tooltip":"Living fate",
    "desc":"An enigmatic scythe used by the handmaiden of death, connected to the far reaches of the underworld. The wielder's life and fate are tied to the blade of the weapon.",
    "util":"The amount of times the weapon can be used are the same as the user's current hitpoints. When the weapon is used, the user loses a hitpoint. If an enemy attempts to drain a use from the weapon, the user loses a hitpoint instead. "
    },
    {
    "img":"media/zsademiekka.png",
    "name":"Z-saber",
    "dmg":"1",
    "range":"2",
    "use":"6",
    "price":"800",
    "tooltip":"Three-slash combo",
    "desc":"A compact and lightweight beamsword from a far-away world. The lightness of this glowing green saber makes it optimal for fast-paced combat situations.",
    "util":"Can be used three times per one turn. The user may do other actions between the uses."
    },
    {
    "img":"media/verinenkoukku.png",
    "name":"A bloody hook",
    "dmg":"-",
    "range":"3",
    "use":"4",
    "price":"700",
    "tooltip":"It's just catsup.",
    "desc":"A large rusted hook that has been submerged in some red liquid. Looks kind of like rotten ketchup but could be anything, really. Tasting not recommended.",
    "util":"The user takes one random card from the targeted enemy."
    },
    {
    "img":"media/teknonoppa.png",
    "name":"Teknodie",
    "dmg":"-",
    "range":"-",
    "use":"2",
    "price":"800",
    "tooltip":"Try again",
    "desc":"Forget about those old boring analog dice and welcome yourself to the future! These technologically advanced dice are made from pure energy and contain many exciting new features, such as a calendar and an an alarm clock.",
    "util":"The user receives an entirely new turn."
    },
    {
    "img":"media/partatera.png",
    "name":"Razor blade",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"400",
    "tooltip":"Slit your wrists",
    "desc":"Sweet pain. Remember to go along the street, not across.",
    "util":"The user gains 300 points and loses one hitpoint."
    },
    {
    "img":"media/taikaluoti20.png",
    "name":"Magic bullet v2.0",
    "dmg":"99",
    "range":">5<",
    "use":"1",
    "price":"500",
    "tooltip":"Banned in 57 countries",
    "desc":"A nasty, lethal modification of the magic bullet rune. Fires an incredibly powerful bolt of light and energy that liquifies the targets internal organs in milliseconds. Developed by tauredian extremists during world war III, the rune is considered to be so cruel that the international humanitarian law forbids it's usage in battle. Despite all this, the incapabilities considering it's effective range make the rune unwieldy to use in regular combat situations.",
    "util":"Hyökkäys toimii ainoastaan viiden ruudun päässä sijaitsevaan kohteeseen."
    },
    {
    "img":"media/antimiekka.png",
    "name":"Antisword",
    "dmg":"1",
    "range":"1",
    "use":"4",
    "price":"800",
    "tooltip":"Really unreal",
    "desc":"A sword brought here from a parallel universe. Due to a temporal glitch that occurred during the process of intergalactic transportation, some of the information was lost in a void and the sword did not materialize properly. The sword, as it currently exists on this timeline, is in an incredibly unstable state and using it may have irreversible effects on the world as we know it.",
    "util":"The targeted enemy loses 200 points."
    },
    {
    "img":"media/isolaastari.png",
    "name":"Big bandage",
    "dmg":"-",
    "range":"-",
    "use":"3",
    "price":"700",
    "tooltip":"For big owies!",
    "desc":"Did you get stabbed? Shot by an assault rifle? Worry not! This massive bandage uses nanotechnology to cure even the bigger ouchies in mere seconds.",
    "util":"The user heals two hitpoints."
    },
    {
    "img":"media/adrestiantera.png",
    "name":"The blade of Adrestia",
    "dmg":"-",
    "range":"3",
    "use":"5",
    "price":"700",
    "tooltip":"Holy retribution",
    "desc":"The holy sword used by the god of balance that was sent away to a void thousands of years ago. A bond between good and evil is tied to the blade of the weapon.",
    "util":"Sets the targeted enemy's hitpoints to be the same amount as the user's."
    },
    {
    "img":"media/rikasote.png",
    "name":"Rich hold",
    "dmg":"-",
    "range":"2",
    "use":"3",
    "price":"700",
    "tooltip":"Take what you deserve",
    "desc":"Maaginen riimu. Käyttää telekineettistä energiaa ja liikuttaa kolikoita sun muita arvoesineitä. Erityisessä suosiossa pienissä kriminaalirganisaatioissa.",
    "util":"Käyttäjä ottaa hyökkäyksen kohteelta 200 pistettä."
    },
    {
    "img":"media/heikentavaote.png",
    "name":"Weakening hold",
    "dmg":"-",
    "range":"2",
    "use":"3",
    "price":"500",
    "tooltip":"Please, no violence!",
    "desc":"Maaginen riimu. Riimun energia tylsyttää mahdolliset terävät reunat ja vaporisoi ruudin. Yleisesti virkavallan käytössä.",
    "util":"Käyttäjä voi poistaa joltain hyökkäyksen kohteen aseelta yhden osumapisteen."
    },
    {
    "img":"media/jaatavaote.png",
    "name":"Freezer hold",
    "dmg":"-",
    "range":"2",
    "use":"3",
    "price":"400",
    "tooltip":"-50°C",
    "desc":"Maaginen riimu. Riimun energiä viilentää ilmaa huomattavasti. Hyödyllinen, jos vaikka pakastin hajoaa tai jotain.",
    "util":"Hyökkäyksen kohde liikkuu 5 ruutua vähemmän seuraavalla vuorollaan."
    },
    {
    "img":"media/pimeaote.png",
    "name":"Dark hold",
    "dmg":"-",
    "range":"5",
    "use":"3",
    "price":"400",
    "tooltip":"I'm moving on my own",
    "desc":"Maaginen riimu. Erittää heikohkoa telekineettistä energiaa, jota pystyy käyttää pienien-keskikokoisten objektien ja asioiden liikuttamiseen. Hyödyllinen, jos haluat vaikka sisustaa kotisi uusiksi tai jotain.",
    "util":"Käyttäjä voi siirtää hyökkäyksen kohdetta 2 ruutua mihin tahansa suuntaan."
    },
    {
    "img":"media/millennium.gif",
    "name":"Millennium",
    "dmg":"3",
    "range":"6",
    "use":"6",
    "price":"2200",
    "tooltip":"Forever",
    "desc":"An incredibly powerful laserrifle from the far future. Fires a projectile that moves at three times the speed of light. The technology behind this weapon is far beyond our current understanding.",
    "util":"Hyökkäystä voi käyttää 2 kertaa vuoron aikana."
    },
    {
    "img":"media/giga.gif",
    "name":"Gigatechnical",
    "dmg":"4",
    "range":"8",
    "use":"4",
    "price":"2200",
    "tooltip":"Seek and destroy",
    "desc":"---",
    "util":"Hyökkäyksen osumaetäisyys on vapaasti ohjattavissa 8 ruutua."
    },
    {
    "img":"media/betel.gif",
    "name":"Betelgeuze",
    "dmg":"5",
    "range":"7x7",
    "use":"4",
    "price":"2200",
    "tooltip":"BLOW UP EVERYTHING!!",
    "desc":"---",
    "util":"---"
    },
    {
    "img":"media/atma.gif",
    "name":"Atma",
    "dmg":"8",
    "range":"3",
    "use":"4",
    "price":"2200",
    "tooltip":"Life",
    "desc":"---",
    "util":"---"
    },
    {
    "img":"media/ame.gif",
    "name":"Ame no Nuhoko",
    "dmg":"4",
    "range":"4",
    "use":"5",
    "price":"2200",
    "tooltip":"Creation",
    "desc":"---",
    "util":"---"
    },
    {
    "img":"media/orionis.gif",
    "name":"Orionis",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"2200",
    "tooltip":"Heaven",
    "desc":"---",
    "util":"---"
    },
    {
    "img":"media/bootes.gif",
    "name":"Boötes",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"2200",
    "tooltip":"Void",
    "desc":"---",
    "util":"---"
    }
]
var cards2 = 
  [
    {
    "img":"media/koukkusauva.png",
    "name":"Long hookstick",
    "tooltip":"Extend your grip",
    "desc":"Insinööriajattelun mestarinäyte, pitkä sauva jonka kärki on taitettu koukuksi. Toimii myös selänrapsuttimena! Mitä muuta ihminen edes tarvitsee?!",
    "util":"Kaikkien käyttäjän aseiden hyökkäysetäisyys +1.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/savuke.png",
    "name":"Cigarette",
    "tooltip":"You're cool now.",
    "desc":"Tupakointi tappaa. Rökning döda.",
    "util":"Käyttäjä saa 200 pistettä aina ottaessaan vahinkoa.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/pyhamanteli.png",
    "name":"Holy almond",
    "tooltip":"From the heavens",
    "desc":"Täysin tavallinen manteli, joka on jostain syystä siunattu pyhällä energialla. Kuka siunaisi mantelin ja miksi? Ken tietää.",
    "util":"Jos käyttäjällä on 2 osumapistettä tai enemmän, tämä jää yhteen osumapisteeseen vaikka vihollisen hyökkäys olisi fataali.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/sydanriipus.png",
    "name":"<3 necklace",
    "tooltip":"The power of love",
    "desc":"Kaunis sydämen muotoinen riipus. Erinomainen lahjaidea rakkaalle, tai henkilölle jolla on ongelmia terveytensä kanssa.",
    "util":"Jos käyttäjällä on vuoron alussa < 3 osumapistettä, tämä parantaa yhden osumapisteen.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/muistikampa.png",
    "name":"Stick of RAM",
    "tooltip":"8GB DDR3",
    "desc":"Tietokoneen keskusmuistia. Todella vanhaa teknologiaa...",
    "util":"Käyttäjä voi pitää kädessään rajattoman määrän punaisia kortteja.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/demoninsarvi.png",
    "name":"Demon horn",
    "tooltip":"Internal rage >:(",
    "desc":"Pieni ja siro sarvi jostain kaukaisesta maailmasta. Sarvi hohtaa vaaleanpunaisena, ja tekee käyttäjän jostain syystä hyvin aggressiiviseksi.",
    "util":"Kaikkien käyttäjän aseiden vahinko +1.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/jeesusteippi.png",
    "name":"Duct tape",
    "tooltip":"NOT duck tape. Get real.",
    "desc":"Tunnetaan ehkä paremmin nimellä ilmastointiteippi. Ei ole mitään asiaa missään maailmaassa mitä tämä legendaarinen teippi ei korjaisi.",
    "util":"Käyttäjä voi 'yhdistää' kaksi asettaan ja hyökätä näillä samanaikaisesti. Kummankin aseen vaikutukset ovat voimassa, mutta vahinko, etäisyys sekä käyttökerrat määrittyvät aseen mukaan jolla nämä arvot ovat korkeammat. Aseilla ei voi tämän jälkeen enää hyökätä erikseen.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/neliaplia.png",
    "name":"4-leaf clover",
    "tooltip":"Ikuinen rikkaus",
    "desc":"Nelilehtisten apiloiden kerrotaan lupaavan hyvää onnea, mutta viisi lehteä? Kuusi lehteä? Huonoja asioita tiedossa, man.",
    "util":"Käyttäjä saa 100 pistettä joka vuoronsa alussa.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/combobulaattori.png",
    "name":"Combobulator",
    "tooltip":"combobulates, duh",
    "desc":"Todella kummallinen... teknologinen kuutio. Siniseen suppiloon on piirretty tussilla epämääräisesti miekan kuva, ja punaiseen paljon dollarimerkkejä. Kuviot näyttää joltain viisi-vuotiaan raapustuksilta...",
    "util":"Milloin tahansa pelin aikana, käyttäjä voi vaihtaa yhden aseensa joko 2 osumapisteeseen tai 300 pisteeseen.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/opiskelijakortti.png",
    "name":"Student ID",
    "tooltip":"Whose is it?!",
    "desc":"Jonkin kaukaisen korkeakoulun opiskelijakortti. Kortti on huonossa kunnossa, likainen ja kulunut. Sen teksteistä on vaikea saada selvää...",
    "util":"Käyttäjä saa jokaisesta kaupan tuotteesta 100 pisteen alennuksen.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/ristiriipus.png",
    "name":"Cross necklace",
    "tooltip":"Blessed protection",
    "desc":"Kaunis kultainen risti. Koruun sulautettu jalokivi on siunattu pyhällä energialla.",
    "util":"Aina kun käyttäjä on ottamassa vahinkoa, tämä heittää noppaa. Jos luku on 6, käyttäjä ei ota vahinkoa.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/d6.png",
    "name":"D6",
    "tooltip":"A better hand",
    "desc":"Kuusivuinen noppa. Kätevä jos haluaa pelata lautapeleja tai jotain, tosin kuka edes pelaa lautapelejä nykyään hahhahaha",
    "util":"Aina vuoronsa alussa, käyttäjä voi vaihtaa haluamansa määrän punaisia kortteja uusiin.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/kysymysriipus.png",
    "name":'"?" necklace',
    "tooltip":"wha",
    "desc":"Mysteerinen kysymysmerkkiriipus. Koru saattaa satunnaisesti päästellä kummallisia ääniä. Saattaa myös repäistä hauskan vitsin aina silloin tällöin.",
    "util":'Aina vuoronsa alussa, käyttäjä voi halutessaan nostaa vihreän "?" kortin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/illuusio.png",
    "name":"Illusion",
    "tooltip":"Mindfreak",
    "desc":"Ovatko viivat suorassa vai vinossa, hä, hä?!",
    "util":"Käyttäjä voi liikkua valkoisten tyhjien kohtien läpi ja siirtyä suoraan tyhjän kohdan toisella puolella olevaan ruutuun.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/litteaarkku.png",
    "name":"Flat chest",
    "tooltip":"But a lovely treasure",
    "desc":"You can't fit a lot of things in this tiny chest, but it's the thought that counts. There's a lock mechanism, but it doesn't appear to be functional...",
    "util":"The user receives all points 200 and under as double.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/aktiiviranneke.png",
    "name":"Activity tracker",
    "tooltip":"Up, you lazybones",
    "desc":"Kätevä ranteen ympärille sidottava kapistus, joka laskee kaikenlaista tärkeää käyttäjän askelmäärästä päivittäiseen kalorinkulukseen. Toimii vielä jotenkuten, vaikka ajurit kylläkin kaipaisivat pientä päivittämistä.",
    "util":"Aina kun käyttäjä liikku 6 ruutua tai enemmän kerralla, tämä saa 300 pistettä.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    },
    {
    "img":"media/antimateria.png",
    "name":"Antimatter",
    "tooltip":"Doesn't even matter",
    "desc":"Kummallinen ja vaarallinen aine, joka on kerätty jostain kaukaisesta avaruudesta. Ainetta on käytetty jo vuosikausia kloonaamisessa. Ei saa missään tapauksessa olla kosketuksessa paljasta ihoa vasten.",
    "util":"Käyttäjä voi vuorollaan täyttää jonkun aseensa osumapisteet, mutta menettää yhden osumapisteen + aseen hinnan määrän pisteitä.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-"
    }  
]
var cards3 = 
  [
    {
    "img":"media/teleport.png",
    "name":"Teleport",
    "util":"Käyttäjä siirtyy kotiruutuunsa.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/puuska.png",
    "name":"Gust",
    "util":"Siirtää vihollista 3 ruutua taaksepäin, käyttöetäisyys 2 ruutua.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/puhallin.png",
    "name":"Blow",
    "util":"Siirtää vihollista 5 ruutua taaksepäin, käyttöetäisyys 2 ruutua.",
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/mysteeri.png",
    "name":"Mystery!",
    "util":'Käyttäjä nostaa 3 vihreää "?" korttia.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/megamysteeri.png",
    "name":"Megamystery!!",
    "util":'Käyttäjä nostaa 4 vihreää "?" korttia.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/wtf.png",
    "name":"What the hell",
    "util":'Käyttäjä nostaa 5 vihreää "?" korttia.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/booster.png",
    "name":"Booster",
    "util":'Käyttäjä voi siirtyä 1-2 ruutua eteenpäin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/bigbooster.png",
    "name":"Big booster",
    "util":'Käyttäjä voi siirtyä 1-3 ruutua eteenpäin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/bbbooster.png",
    "name":"BBBBBooster",
    "util":'Käyttäjä voi siirtyä 1-5 ruutua eteenpäin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/korjaus.png",
    "name":"Fix",
    "util":'Käyttäjä parantaa yhden osumapisteen jollekkin aseelleen.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/kaivuu.png",
    "name":"Dig",
    "util":'Toimii kertakäyttöisenä hakkuna.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/napistus.png",
    "name":"Steal",
    "util":'Käyttäjä varastaa viholliselta 100 pistettä, käyttöetäisyys 1 ruutu.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/kilpi.png",
    "name":"Shield",
    "util":'Kun käyttäjä on ottamassa vahinkoa, hän voi käyttää korttia ja välttää vahingon.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/ensiapu.png",
    "name":"First aid",
    "util":'Käyttäjä parantaa yhden osumapisteen.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/magneto.png",
    "name":"Magneto",
    "util":' Käyttäjä vetää vihollisen viereiseen ruutuun, käyttöetäisyys 5 ruutua.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/paivitys.png",
    "name":"Restock",
    "util":'Vaihtaa kaikki kaupan tuotteet uusiin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/solve.png",
    "name":"solve( )",
    "util":'Käyttäjä voi katsoa kummankin "?" pakan päällimmäisen kortin.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/jumalasilma.png",
    "name":"The eye of God",
    "util":'Käyttäjä voi katsoa kenen tahansa pelaajan kaikki punaiset kortit.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/harhautus.png",
    "name":"Deke",
    "util":'Käyttäjä poistaa vihollisen kädestä 2 satunnaista punaista korttia, käyttöetäisyys 1 ruutu.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/lahja.png",
    "name":"Gift!",
    "util":'Vihollinen nostaa 2 "?" korttia, käyttöetäisyys 2 ruutua.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/epasuoraisku.png",
    "name":"Indirect attack",
    "util":'Poistaa joltain vihollisen aseelta yhden osumapisteen.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/diili.png",
    "name":"Deal",
    "util":'Käyttäjä vaihtaa yhden aseistaan johonkin vihollisen aseeseen, käyttöetäisyys 1 ruutu.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/teroitus.png",
    "name":"Sharpen",
    "util":'Käyttäjän aseiden vahinko +1 yhden vuoron ajan.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/pitkitys.png",
    "name":"Elongate",
    "util":'Käyttäjän aseiden osumaetäisyys +1 yhden vuoron ajan.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/teleother.png",
    "name":"Teleother",
    "util":'Käyttäjä voi siirtää vihollisen mihin tahansa ruutuun, käyttöetäisyys 2 ruutua.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/teleport20.png",
    "name":"Teleport v2.0",
    "util":'Käyttäjä voi siirtyä mihin tahansa ruutuun.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
    {
    "img":"media/napistus20.png",
    "name":"Steal v2.0",
    "util":'Käyttäjä varastaa viholliselta 200 pistettä, käyttöetäisyys 2 ruutua.',
    "dmg":"-",
    "range":"-",
    "use":"-",
    "price":"-",
    "desc":"-",
    "tooltip":"-"
    },
]